version: "3"
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"

  api:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: pp/backend
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db

  client:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: pp/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - api
